package com.inet.lib.less;

/**
 * Represents the compression options available for code generated by the
 * compiler.
 * @author jfennell.
 */
  public enum CompressionStatus {
    UNCOMPRESSED,
    COMPRESSED;

    CompressionStatus() {}
}
